lint.select = [
    "F", # pyflakes
    "E", # pycodestyle
    "D", # pydocstyle
    "W", # pycodestyle
    "Q", # flake8-quotes
    #"N", # pep8-naming (TODO enable this post BH)
    "B", # flake8-bugbear
    "UP", # pyupgrade
    "RUF", # ruff
    "C4", # flake8-comprehensions
    #"C90", # mccabe (TODO enable this post BH)
    "PTH", # flake8-use-pathlib
    #"SIM", # flake8-simplify (TODO potentially enable this post BH)
    "TID", # flake8-tidy-imports
    "I", # isort
]
lint.ignore = [
    "F403", "E402", "E501",
    "W191", "E111", "E114", "E117", # (disable ruff-format problematic rules)
    "D206", "D300", # (disable ruff-format problematic rules)
    "Q000", "Q001", "Q002", "Q003", # (disable ruff-format problematic rules)
    "COM812", "COM819", "ISC001", "ISC002", # (disable ruff-format problematic rules)
    "ANN101", "ANN102", # (disable unnecessary flake8-annotations rules)
    "ANN401", # (disable "annoying" flake8-annotations rules)
]

lint.fixable = [
    "A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W",
    "ANN", "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FBT",
    "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH",
    "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"
]
exclude = [
    ".git",
    ".hg",
    ".mypy_cache",
    ".ruff_cache",
    ".tox",
    ".venv",
    "*.ipynb",
    "__pypackages__",
    "_build",
    "build",
    "dist",
    "node_modules",
    "venv",
    "notebooks",
    "ext",
    "deps",
    "migrations",
]
target-version = "py311"
line-length = 88
lint.unfixable = []

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
docstring-code-format = true

[lint.per-file-ignores]
"__init__.py" = ["F401"]

[lint.isort]
combine-as-imports = true
force-wrap-aliases = true
force-sort-within-sections = false
split-on-trailing-comma = false

[lint.mccabe]
# currently uses cyclomatic complexity
max-complexity = 10
# We should switch to https://www.sonarsource.com/docs/CognitiveComplexity.pdf
# https://github.com/astral-sh/ruff/issues/2418

[lint.pydocstyle]
convention = "google"

[lint.flake8-tidy-imports]
ban-relative-imports = "parents"

[lint.flake8-quotes]
docstring-quotes = "double"

[lint.flake8-bugbear]
extend-immutable-calls = ["typer.Argument", "fastapi.Depends"]

[lint.flake8-annotations]
mypy-init-return = true